#!/usr/bin/sh
sed -E 's/([0-9a-zA-Z])([\xe4\xb8\x80-\xe9\xbe\xa5])/\1 \2/g' $1 -i
sed -E 's/([\xe4\xb8\x80-\xe9\xbe\xa5])([0-9a-zA-Z])/\1 \2/g' $1 -i
sed -E 's/([0-9a-zA-Z%])。/\1．/g' $1 -i
sed -E 's/^ +\n$/\n/g' $1 -i
sed -E 's/^([^ ]+) +/\1 /g' $1 -i
sed -E s/\n\n\n+/\n\n/g $1 -i
sed -E "y/“”/「」/" $1 -i
